import { Open_Sans } from 'next/font/google'

import type { Metadata } from 'next'

import './globals.css'

export const metadata: Metadata = {
  title: {
    template: '%s | Netflix Clone',
    default: 'Netflix Clone',
  },
  description: 'Generated by create next app',
}

const openSans = Open_Sans({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-open-sans',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={openSans.variable} suppressHydrationWarning>
      <body>{children}</body>
    </html>
  )
}
